name: Terraform Task2Advanced

on:
  workflow_dispatch:
    inputs:
      apply:
        description: "Run terraform apply"
        required: true
        default: "false"
        type: choice
        options:
          - "false"
          - "true"

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.YC_S3_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.YC_S3_SECRET }}

    defaults:
      run:
        working-directory: Task2Advanced

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.0

      - name: Terraform init
        run: terraform init

      - name: Terraform plan
        run: terraform plan

      - name: Terraform apply (manual approval inside job)
        if: ${{ github.event.inputs.apply == 'true' }}
        run: terraform apply -auto-approve
